# Generated by Django 5.1.2 on 2024-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_task_description_de_task_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
